baseURL = 'michaelfransen.com'
languageCode = 'en-us'
title = 'Michael Fransen'
theme = 'paper'

[params]
  color = 'light'
  github="michaelfransen"
  instagram="michaelfransen"
  threads="michaelfransen"
  linkedin="michaelfransen"
  rss = true

  name = 'Michael Fransen'
  bio = '''
  ğŸ’» Software Engineer
  ğŸ“ San Francisco, California
  '''
  avatar = 'https://micro.blog/michaelfransen/avatar.jpg'
  monoDarkIcon = true
